services:
  - type: web
    name: strapi
    env: node
    repo: https://github.com/SteaceP/api-test.git
    region: ohio
    plan: starter
    branch: main
    buildCommand: yarn install && yarn build
    startCommand: yarn start
    healthCheckPath: /_health
    domains:
      - test.coderage.pro
    headers:
      - path: /*
        name: X-Frame-Options
        value: sameorigin
    envVars:
      - key: NODE_VERSION
        value: ~16.17.0
      - key: NODE_ENV
        value: production
      - key: CLOUDINARY_NAME
        sync: false
      - key: CLOUDINARY_KEY
        sync: false
      - key: CLOUDINARY_SECRET
        sync: false
      - key: SENDGRID_API_KEY
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: strapi
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: ADMIN_JWT_SECRET
        generateValue: true
      - key: APP_KEYS
        generateValue: true
      - key: API_TOKEN_SALT
        generateValue: true


databases:
  - name: strapi
    plan: starter
